export const original = {
  books: [
    { id: "b1", title: "Exploring Stories Together", author: "Lydia Monroe", subjects: ["ELA", "Reading"], gradeLevels: ["K", 1, 2], curriculumIds: ["c3"], resourceIds: ["r1", "r5"] },
    { id: "b2", title: "Phonics and Early Reading Skills", author: "James Carter", subjects: ["ELA", "Phonics"], gradeLevels: ["K", 1], curriculumIds: ["c2"], resourceIds: ["r6"] },
    { id: "b3", title: "Math Adventures: Numbers and Patterns", author: "Sophie Lin", subjects: ["Math"], gradeLevels: [1, 2, 3], curriculumIds: ["c5"], resourceIds: ["r2", "r7"] },
    { id: "b4", title: "Building Strong Writers", author: "Evelyn Harper", subjects: ["ELA", "Writing"], gradeLevels: [2, 3, 4], curriculumIds: ["c1"], resourceIds: ["r8"] },
    { id: "b5", title: "Science Around Us", author: "Olivia Grant", subjects: ["Science"], gradeLevels: [1, 2, 3], curriculumIds: ["c9"], resourceIds: ["r3", "r9"] },
    { id: "b6", title: "Hands-On Life Science", author: "Nathan Flores", subjects: ["Science", "Biology"], gradeLevels: [3, 4, 5], curriculumIds: ["c9"], resourceIds: ["r10"] },
    { id: "b7", title: "World Stories for Young Readers", author: "Marisa Bennett", subjects: ["ELA", "Literature"], gradeLevels: [2, 3, 4], curriculumIds: ["c3"], resourceIds: ["r11"] },
    { id: "b8", title: "Early American History", author: "Caroline Pierce", subjects: ["Social Studies", "History"], gradeLevels: [3, 4, 5], curriculumIds: ["c12"], resourceIds: ["r4", "r12"] },
    { id: "b9", title: "Problem Solving Strategies", author: "Gregory Shaw", subjects: ["Math"], gradeLevels: [4, 5], curriculumIds: ["c7"], resourceIds: ["r13"] },
    { id: "b10", title: "Grammar for Growing Minds", author: "Daniel Reeves", subjects: ["ELA", "Grammar"], gradeLevels: [3, 4, 5], curriculumIds: ["c2"], resourceIds: ["r14"] },

    { id: "b11", title: "Writing with Clarity", author: "Evelyn Harper", subjects: ["ELA"], gradeLevels: [7], curriculumIds: ["c1"], resourceIds: ["r15"] },
    { id: "b12", title: "Words for the Curious Mind", author: "Daniel Reeves", subjects: ["Vocabulary"], gradeLevels: [7], curriculumIds: ["c2"], resourceIds: ["r16"] },
    { id: "b13", title: "Journeys Through Medieval Worlds", author: "Marisa Bennett", subjects: ["Literature"], gradeLevels: [7], curriculumIds: ["c3"], resourceIds: ["r17"] },
    { id: "b14", title: "Foundations of Mathematical Thinking", author: "Steven Cole", subjects: ["Math"], gradeLevels: [7], curriculumIds: ["c5"], resourceIds: ["r18"] },
    { id: "b15", title: "Life Science Explorations", author: "Olivia Grant", subjects: ["Science"], gradeLevels: [7], curriculumIds: ["c8"], resourceIds: ["r19"] },

    { id: "b16", title: "Writing with Purpose", author: "Evelyn Harper", subjects: ["ELA"], gradeLevels: [8], curriculumIds: ["c1"], resourceIds: ["r20"] },
    { id: "b17", title: "Advanced Vocabulary Builder", author: "Daniel Reeves", subjects: ["Vocabulary"], gradeLevels: [8], curriculumIds: ["c2"], resourceIds: ["r21"] },
    { id: "b18", title: "Prealgebra in Action", author: "Steven Cole", subjects: ["Math"], gradeLevels: [8], curriculumIds: ["c5"], resourceIds: ["r22"] },
    { id: "b19", title: "Physical Science Investigations", author: "Olivia Grant", subjects: ["Science"], gradeLevels: [8], curriculumIds: ["c8"], resourceIds: ["r23"] },
    { id: "b20", title: "American Beginnings to WWI", author: "Anthony Delgado", subjects: ["History"], gradeLevels: [8], curriculumIds: ["c11"], resourceIds: ["r24"] },

    { id: "b21", title: "Literature and Composition I", author: "Evelyn Harper", subjects: ["ELA"], gradeLevels: [9], curriculumIds: ["c1"], resourceIds: ["r25"] },
    { id: "b22", title: "English 9: Classic Readings", author: "Noah Bennett", subjects: ["ELA"], gradeLevels: [9], curriculumIds: ["c13"], resourceIds: ["r26"] },
    { id: "b23", title: "Algebra I Concepts", author: "Gregory Shaw", subjects: ["Math"], gradeLevels: [9], curriculumIds: ["c7"], resourceIds: ["r27"] },
    { id: "b24", title: "Biology Foundations", author: "Olivia Grant", subjects: ["Science"], gradeLevels: [9], curriculumIds: ["c8"], resourceIds: ["r28"] },
    { id: "b25", title: "Biology: Life Systems", author: "Laura Jenkins", subjects: ["Science"], gradeLevels: [9], curriculumIds: ["c4"], resourceIds: ["r29"] },

    { id: "b26", title: "Literature and Composition II", author: "Evelyn Harper", subjects: ["ELA"], gradeLevels: [10], curriculumIds: ["c1"], resourceIds: ["r30"] },
    { id: "b27", title: "World Literature Classics", author: "Margaret Ellis", subjects: ["ELA"], gradeLevels: [10], curriculumIds: ["c8"], resourceIds: ["r31"] },
    { id: "b28", title: "Geometry Essentials", author: "Gregory Shaw", subjects: ["Math"], gradeLevels: [10], curriculumIds: ["c7"], resourceIds: ["r32"] },
    { id: "b29", title: "Chemistry: Matter and Change", author: "Laura Jenkins", subjects: ["Science"], gradeLevels: [10], curriculumIds: ["c4"], resourceIds: ["r33"] },
    { id: "b30", title: "Modern World History", author: "Laura Jenkins", subjects: ["History"], gradeLevels: [10], curriculumIds: ["c4"], resourceIds: ["r34"] },

    { id: "b31", title: "American Literature", author: "Evelyn Harper", subjects: ["ELA"], gradeLevels: [11], curriculumIds: ["c1"], resourceIds: ["r35"] },
    { id: "b32", title: "Algebra II Mastery", author: "Gregory Shaw", subjects: ["Math"], gradeLevels: [11], curriculumIds: ["c7"], resourceIds: ["r36"] },
    { id: "b33", title: "Physics Principles", author: "Laura Jenkins", subjects: ["Science"], gradeLevels: [11], curriculumIds: ["c4"], resourceIds: ["r37"] },
    { id: "b34", title: "Making America", author: "Robert Kendall", subjects: ["US History"], gradeLevels: [11], curriculumIds: ["c18"], resourceIds: ["r38"] },
    { id: "b35", title: "America Through the Lens", author: "Anthony Delgado", subjects: ["US History"], gradeLevels: [11], curriculumIds: ["c11"], resourceIds: ["r39"] },

    { id: "b36", title: "British Literature Reader", author: "Margaret Ellis", subjects: ["ELA"], gradeLevels: [12], curriculumIds: ["c8"], resourceIds: ["r40"] },
    { id: "b37", title: "Precalculus Foundations", author: "Gregory Shaw", subjects: ["Math"], gradeLevels: [12], curriculumIds: ["c7"], resourceIds: ["r41"] },
    { id: "b38", title: "Economics in Action", author: "Laura Jenkins", subjects: ["Economics"], gradeLevels: [12], curriculumIds: ["c4"], resourceIds: ["r42"] },
    { id: "b39", title: "American Government", author: "Anthony Delgado", subjects: ["Government"], gradeLevels: [12], curriculumIds: ["c11"], resourceIds: ["r43"] },
    { id: "b40", title: "Environmental Science", author: "Olivia Grant", subjects: ["Science"], gradeLevels: [12], curriculumIds: ["c8"], resourceIds: ["r44"] }
  ],

  curriculums: [
    { id: "c1", name: "Essentials in Writing" },
    { id: "c2", name: "Wordly Wise" },
    { id: "c3", name: "Moving Beyond the Page" },
    { id: "c4", name: "McGraw Hill" },
    { id: "c5", name: "Thinkwell" },
    { id: "c6", name: "Live Online Math" },
    { id: "c7", name: "Saxon" },
    { id: "c8", name: "Oak Meadow" },
    { id: "c9", name: "Elemental Science" },
    { id: "c10", name: "History Odyssey" },
    { id: "c11", name: "Cengage" },
    { id: "c12", name: "Bookshark" },
    { id: "c13", name: "Write at Home" },
    { id: "c14", name: "Blackbird and Company" },
    { id: "c15", name: "Mr. D Math" },
    { id: "c16", name: "The Classical Historian" },
    { id: "c17", name: "Miss Crady the Math Lady" },
    { id: "c18", name: "Making America" }
  ],

  resources: [
    { id: "r1", bookId: "b1", title: "Reading Activity Sheets" },
    { id: "r2", bookId: "b3", title: "Math Workbook" },
    { id: "r3", bookId: "b5", title: "Science Kit" },
    { id: "r4", bookId: "b8", title: "Timeline Activities" },

    { id: "r5", bookId: "b1", title: "Story Comprehension Questions" },
    { id: "r6", bookId: "b2", title: "Phonics Flashcards" },
    { id: "r7", bookId: "b3", title: "Practice Worksheets" },
    { id: "r8", bookId: "b4", title: "Writing Prompts Pack" },
    { id: "r9", bookId: "b5", title: "Experiment Guide" },
    { id: "r10", bookId: "b6", title: "Lab Activity Sheets" },
    { id: "r11", bookId: "b7", title: "Reading Journal" },
    { id: "r12", bookId: "b8", title: "Map Activities" },
    { id: "r13", bookId: "b9", title: "Problem Sets" },
    { id: "r14", bookId: "b10", title: "Grammar Exercises" },

    { id: "r15", bookId: "b11", title: "Essay Practice Guide" },
    { id: "r16", bookId: "b12", title: "Vocabulary Quizzes" },
    { id: "r17", bookId: "b13", title: "Literature Questions" },
    { id: "r18", bookId: "b14", title: "Math Exercises" },
    { id: "r19", bookId: "b15", title: "Science Labs" },

    { id: "r20", bookId: "b16", title: "Writing Worksheets" },
    { id: "r21", bookId: "b17", title: "Word Practice Sheets" },
    { id: "r22", bookId: "b18", title: "Problem Workbook" },
    { id: "r23", bookId: "b19", title: "Lab Manual" },
    { id: "r24", bookId: "b20", title: "History Timeline Kit" },

    { id: "r25", bookId: "b21", title: "Composition Workbook" },
    { id: "r26", bookId: "b22", title: "Reading Logs" },
    { id: "r27", bookId: "b23", title: "Algebra Practice Sheets" },
    { id: "r28", bookId: "b24", title: "Biology Worksheets" },
    { id: "r29", bookId: "b25", title: "Lab Experiments" },

    { id: "r30", bookId: "b26", title: "Essay Writing Pack" },
    { id: "r31", bookId: "b27", title: "Literature Analysis Guide" },
    { id: "r32", bookId: "b28", title: "Geometry Workbook" },
    { id: "r33", bookId: "b29", title: "Chemistry Lab Kit" },
    { id: "r34", bookId: "b30", title: "History Review Sheets" },

    { id: "r35", bookId: "b31", title: "Literary Analysis Pack" },
    { id: "r36", bookId: "b32", title: "Algebra II Exercises" },
    { id: "r37", bookId: "b33", title: "Physics Lab Guide" },
    { id: "r38", bookId: "b34", title: "US History Activities" },
    { id: "r39", bookId: "b35", title: "Document Analysis Sheets" },

    { id: "r40", bookId: "b36", title: "Reading Response Journal" },
    { id: "r41", bookId: "b37", title: "Precalculus Problem Sets" },
    { id: "r42", bookId: "b38", title: "Economics Case Studies" },
    { id: "r43", bookId: "b39", title: "Government Worksheets" },
    { id: "r44", bookId: "b40", title: "Environmental Projects Guide" }
  ]
};